[package]
name = "casbin-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sqlx-adapter = {version = "0.4", default-features = false, features = ["mysql","runtime-tokio-native-tls"]}
