refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} {l} {t} {f} {L}- {m}{n}"
      # {M}
  # db:
  #   kind: file
  #   path: "log/db.log"
  #   append: true
  #   encoder:
  #     pattern: "{d} {l} {t} - {m}{n}"
  hello:
    kind: rolling_file
    path: "logs/hello.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: "logs/hello.{}.log"
        count: 100
        base: 1
root:
  level: debug
  appenders:
    - stdout
loggers:
  hello:
    level: info
    appenders:
      - stdout
      - hello
    additive: false