[package]
name = "ui-yew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.19"}
# yew-bootstrap = "0"

[profile.release]
lto = true
opt-level = 3