[package]
name = "hello-tokio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19", features = ["full"] }
serde = "1.0"
serde_yaml = "0.8"
toml = "0.5"
anyhow = "1.0"
